config/routes.rb
Calendar::Engine.routes.draw do

  scope '(:locale)' do
    get 'events/new_tooltip', to: 'events#new_tooltip'

    post 'events/new', to: 'events#new'

    resources :events
  end

  root to: 'calendar#index'

end

app/models/calendar/event.rb
module Calendar
  class Event < ActiveRecord::Base

    # Allow mass-assignment
    attr_accessible :title, :starts_at, :ends_at, :all_day, :description, :location, :created_at, :updated_at, :color

    validates :starts_at, presence: true
    validates :ends_at, presence: true
    validates :all_day, :inclusion => { :in => [true, false] } # See http://stackoverflow.com/questions/3608076/rails-how-do-i-validate-that-something-is-a-boolean
    validate :validate_ends_at_after_starts_at

    after_initialize :default_values

    # Gets all events ending after a given date
    scope :ending_after, lambda { |date| where("ends_at > ?", date) }

    # Gets all events starting before a given date
    scope :starting_before, lambda { |date| where("starts_at < ?", date) }

    # Frequency for displaying time slots, in minutes.
    # Used by FullCalendar and jQuery timepicker.
    STEP_MINUTE = 30

    # Event length in minutes.
    EVENT_LENGTH = 60

    # Time zone to use inside the views
    TIME_ZONE = 'Paris'

    # Date format to use inside the views.
    DATE_FORMAT = '%Y-%m-%d'
    DATE_FORMAT_PICKER = 'yy-mm-dd' # See http://jqueryui.com/demos/datepicker/

    # Time format to use inside the views.
    TIME_FORMAT = '%I:%M%P'
    TIME_FORMAT_PICKER = 'h:ia' # See https://github.com/jonthornton/jquery-timepicker

    # First day of the week for FullCalendar.
    # 0 means sunday
    # 1 means monday
    FIRST_DAY_OF_WEEK = 0

    # Available colors for an event.
    # Taken from Google Calendar.
    COLORS = {
      green:       '#7bd148',
      bold_blue:   '#5484ed',
      blue:        '#a4bdfc',
      turquoise:   '#46d6db',
      light_green: '#7ae7bf',
      bold_green:  '#51b749',
      yellow:      '#fbd75b',
      orange:      '#ffb878',
      red:         '#ff887c',
      bold_red:    '#dc2127',
      purple:      '#dbadff',
      gray:        '#e1e1e1'
    }

    # Need to override the JSON view to return what FullCalendar is expecting.
    # See http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
    def as_json(options = nil)
      {
        id: id,
        title: title,
        description: description,
        start: starts_at, # ISO 8601, ex: "2011-10-28T01:22:00Z"
        end: ends_at,
        allDay: all_day,
        color: color
      }
    end

    # Returns the event title.
    # Returns '(No title)' if the title does not exist inside the database.
    # TODO Translation + move this to view?
    def title
      title = read_attribute(:title)
      title.blank? ? '(No title)' : title
    end

    private

    # Initializes the attributes with default values.
    # See http://stackoverflow.com/questions/328525/what-is-the-best-way-to-set-default-values-in-activerecord
    # See http://stackoverflow.com/questions/1550688/how-do-i-create-a-default-value-for-attributes-in-rails-activerecords-model
    # See http://stackoverflow.com/questions/1186400/correct-way-to-set-default-values-in-rails
    def default_values
      now = Time.now.round_time(STEP_MINUTE.minutes)
      self.starts_at ||= now
      self.ends_at ||= now + EVENT_LENGTH.minutes
      self.all_day ||= false
      self.color ||= COLORS[:green]
    end

    def validate_ends_at_after_starts_at
      if starts_at && ends_at
        errors.add(:ends_at, "can't be before the starting date") if ends_at < starts_at
      end
    end
  end
end

app/controllers/calendar/application_controller.rb
module Calendar
  class ApplicationController < ActionController::Base

    # Locale
    before_filter :set_locale

    private

    # Sets the locale from parameters.
    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    # Sets the locale as part of the URLs.
    # See http://guides.rubyonrails.org/i18n.html
    # See http://apidock.com/rails/ActionController/Base/default_url_options
    def default_url_options(options = nil)
      { locale: I18n.locale }
    end
  end
end

app/controllers/calendar/calendar_controller.rb
module Calendar
  class CalendarController < ApplicationController

    # Shows the calendar using current date or the provided date if any.
    # If a date is specified, it will move the calendar.
    #
    # GET /calendar
    # GET /calendar?date="2011-10-22T03:20:00Z" => ISO 8601 format, Time.now.utc.iso8601
    # GET /calendar?date="2011-10-22 01:20:00 UTC" => Time.now.utc
    # GET /calendar?date="2011-10-22 03:20:00 +0200" => Time.now
    # GET /calendar?date="2011-10-22 UTC"
    # GET /calendar?date="2011-10-22 +0200"
    # GET /calendar?date="2011-10-22"
    def index
      # ISO 8601 format is not yet fully supported by JavaScript Date object
      # so a string cannot be passed directly to FullCalendar.
      # Let's use a temporary Ruby Time object.
      # See https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Date/parse

      # Time.to_i returns the number of seconds since the Unix epoch.
      # Date JavaScript object constructor takes the number of milliseconds since the Unix epoch.

      @date = Time.parse(params[:date]).to_i * 1000 if params[:date]
    end

  end
end

app/controllers/calendar/events_controller.rb
module Calendar
  class EventsController < ApplicationController
    before_filter :parse_datepair_params

    # GET /events
    # GET /events.json
    def index

      # FullCalendar will hit the index method with query parameters
      # 'start' and 'end' in order to filter the results
      # Format is Unix timestamps (seconds since 1970)
      # Example: GET "/calendar/events?start=1338069600&end=1341698400"
      #
      # Multiple cases:
      #
      #        start      end
      #    ______|_________|______
      #       |_______________|     => OK
      #       |_____|               => OK
      #                 |_____|     => OK
      #            |_____|          => OK
      #     |_|                     => X
      #                       |_|   => X
      #
      # All the events that end after 'start' and that start before end
      # Tous les événements qui finissent après 'start' et qui débutent avant 'end'
      #
      # This will generate the following query:
      # SELECT "calendar_events".* FROM "calendar_events" WHERE (ends_at > '2012-05-26 22:00:00.000000') AND (starts_at < '2012-07-07 22:00:00.000000')

      @events = Event.scoped
      @events = @events.ending_after(Time.at(params['start'].to_i)) if (params['start'])
      @events = @events.starting_before(Time.at(params['end'].to_i)) if (params['end'])

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @events }
      end
    end

    # GET /events/1
    # GET /events/1.json
    def show
      @event = Event.find(params[:id])

      respond_to do |format|
        format.html { render layout: false } # show.html.erb
        format.json { render json: @event }
      end
    end

    # GET /events/new
    # GET /events/new.json
    def new
      @event = Event.new(params[:event])

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @event }
      end
    end

    # GET /events/new_tooltip
    def new_tooltip
      @event = Event.new(params[:event])

      respond_to do |format|
        format.html { render layout: false } # new_tooltip.html.erb
      end
    end

    # GET /events/1/edit
    def edit
      @event = Event.find(params[:id])
    end

    # POST /events
    # POST /events.json
    def create
      @event = Event.new(params[:event])

      respond_to do |format|
        if @event.save
          flash.notice = t('calendar.events.event_created', title: @event.title)
          format.html { redirect_to root_url }
          format.json { render json: @event, status: :created, location: @event }
          format.js # create.js.erb
        else
          format.html { render action: 'new' }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /events/1
    # PUT /events/1.json
    def update
      @event = Event.find(params[:id])

      respond_to do |format|
        if @event.update_attributes(params[:event])
          flash.notice = t('calendar.events.event_updated', title: @event.title)
          format.html { redirect_to root_url }
          format.json { head :ok }
          format.js # update.js.erb
        else
          format.html { render action: 'edit' }
          format.json { render json: @event.errors, status: :unprocessable_entity }
          format.js # update.js.erb
        end
      end
    end

    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event = Event.find(params[:id])
      @event.destroy

      respond_to do |format|
        flash.notice = t('calendar.events.event_deleted', title: @event.title)
        format.html { redirect_to root_url }
        format.json { head :ok }
        format.js # destroy.js.erb
      end
    end

    private

    include DatePairInputHelper

    def parse_datepair_params()
      parse_datepair(params, :event, :starts_at)
      parse_datepair(params, :event, :ends_at)
    end
  end
end

app/helpers/calendar/application_helper.rb
module Calendar
  module ApplicationHelper
  end
end

app/helpers/calendar/calendar_helper.rb
module Calendar
  module CalendarHelper
  end
end

app/helpers/calendar/events_helper.rb
module Calendar
  module EventsHelper

    # Returns an HTML string for the given date pair.
    #
    # See Time#format_datepair
    # See DateHelper#time_tag
    #
    # ==== Example
    #   datepair_tag @event.starts_at, @event.ends_at, @event.all_day
    #   # => 'Tue, January 31, 2:30pm &ndash; 3pm'
    #
    def datepair_tag(starts_at, ends_at, all_day)
      raw "#{Time.format_datepair(starts_at, ends_at, all_day)}"
    end

    # Returns Calendar::Event::COLORS translated for use with simple_form.
    def available_colors_translated
      colors_translated = {}
      Calendar::Event::COLORS.each do |color, hex|
        colors_translated[t("colors.#{color}")] = hex;
      end
      colors_translated
    end
  end
end

app/views/calendar/events/_form.html.erb
<%= simple_form_for(@event, :html => { class: 'form-horizontal' }) do |f| %>
  <br />

  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">×</a>
      <%= notification %>
    </div>
  <% end %>

  <%= f.input :title, autofocus: true, input_html: { class: "input-xlarge" } %>

  <div class="datepair">
    <%= f.input :starts_at, as: :date_pair, input_html: { class: "start" } %>
    <%= f.input :ends_at, as: :date_pair, input_html: { class: "end" } %>
    <%= f.input :all_day, label: false, inline_label: true %>
  </div>

  <%= f.input :location, input_html: { class: "form-horizontal input-xlarge" } %>

  <%= f.input :description, input_html: { class: "input-xlarge", rows: "3" } %>

  <%= f.input :color, collection: available_colors_translated, selected: @event.color %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
    <%= link_to t('.back_to_calendar'), root_path %>
  </div>
<% end %>

app/views/calendar/events/create.js.erb
<%# Trick: removes the tooltip by removing all tooltips %>
removeAllTooltips();

<%# See http://stackoverflow.com/questions/366311/how-do-you-handle-rails-flash-with-ajax-requests %>
$("#flashes").html("<%= escape_javascript(render 'layouts/calendar/flashes') %>");
<% flash.discard %> <%# Don't want the flash to appear when you reload page %>

refetchFullCalendarEvents();

app/views/calendar/events/destroy.js.erb
<%# Removes the tooltip even if it should be gone already because the focus was lost %>
removeTooltip('<%= dom_id(@event) %>');

<%# See http://stackoverflow.com/questions/366311/how-do-you-handle-rails-flash-with-ajax-requests %>
$("#flashes").html("<%= escape_javascript(render 'layouts/calendar/flashes') %>");
<% flash.discard %> <%# Don't want the flash to appear when you reload page %>

refetchFullCalendarEvents();

app/views/calendar/events/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/calendar/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>All day</th>
    <th>Location</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr id=<%= dom_id(event) %>>
    <td><%= event.title %></td>
    <td><%= event.starts_at %></td>
    <td><%= event.ends_at %></td>
    <td><%= event.all_day %></td>
    <td><%= event.location %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Delete', event, confirm: 'Are you sure?', method: :delete, remote: true %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/calendar/events/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/calendar/events/new_tooltip.html.erb
<%= simple_form_for(@event, :remote => true, :html => { class: 'form-vertical' }) do |f| %>
  <div class="control-group">
    <label class="control-label"><%= t('.when') %></label>
    <div class="controls">
      <span class="input uneditable-input"><%= datepair_tag @event.starts_at, nil, @event.all_day %></span>
      <%= f.hidden_field :starts_at %>
      <%= f.hidden_field :ends_at %>
      <%= f.hidden_field :all_day %>
    </div>
  </div>

  <%= f.input :title, autofocus: true %>

  <%= f.button :submit %>
  <%= link_to t('calendar.events.show.edit'), '#', id: 'edit_event' %>
<% end %>

<%= javascript_tag do %>
  <%#
    Update the form when the user clicks on the edit link
    See http://stackoverflow.com/questions/461790/multiple-submit-buttons-forms-in-rails
  %>
  $(document).ready(function() {
    $('#edit_event').click(function() {
      var new_event_form = $('#new_event'); <%# The default form id is 'new_event' %>
      new_event_form.removeAttr('data-remote');
      new_event_form.attr('action', '<%= new_event_path %>');
      new_event_form.attr('method', 'post');
      new_event_form.submit();
    });
  });
<% end %>

app/views/calendar/events/show.html.erb
<%# No layout for this view, see events_controller#show %>

<%= select(:event, :color, available_colors_translated) %>

<p>
  <b><%= t('.when') %></b>
  <%= datepair_tag @event.starts_at, @event.ends_at, @event.all_day %>
</p>

<% if !@event.location.blank? %>
  <p>
    <b><%= t('.location') %></b>
    <%= @event.location %>
  </p>
<% end %>

<%= link_to t('delete'), @event, data: { confirm: t('are_you_sure') }, method: :delete, remote: true %>
|
<%= link_to t('.edit'), edit_event_path(@event) %>

<%= javascript_tag do %>
  $(document).ready(function() {
    var tooltipTitle = $('#ui-tooltip-<%= dom_id(@event) %>-title');
    var colorSelect = $('#event_color');

    <%# Move the color <select> inside the tooltip title %>
    tooltipTitle.prepend(colorSelect);

    colorSelect.simplecolorpicker({
      picker: true
    });

    <%# simplecolorpicker default z-index is 1000, too low for qTip2 z-index which is 15001 %>
    $('.simplecolorpicker.picker').css('z-index', 15002);

    $('.simplecolorpicker.icon').css({
      <%# Back to the defaults set by Twitter Bootstrap %>
      'font-size': '13px',
      'line-height': '18px',

      <%# Margin between the picker icon and the tooltip text %>
      'margin-right': '4px'
    });
  });
<% end %>

app/views/calendar/events/update.js.erb
<%# See http://stackoverflow.com/questions/366311/how-do-you-handle-rails-flash-with-ajax-requests %>
$("#flashes").html("<%= escape_javascript(render 'layouts/calendar/flashes') %>");
<% flash.discard %> <%# Don't want the flash to appear when you reload page %>